export const notesTypes = {
  ADD_NEW_NOTE: "ADD_NEW_NOTE",
  DELETE_NOTE: "DELETE_NOTE",
  UPDATE_NOTE: "UPDATE_NOTE",
  LOAD_NOTE: "LOAD_NOTE",
  IMG_URL: "IMG_URL",
  SET_ACTIVE_NOTE: "SET_ACTIVE_NOTE",
  LOGOUT_CLEAN_NOTE: "LOGOUT_CLEAN_NOTE",
};
